runtime: python312  # Match your Python version

entrypoint: uvicorn main:app --host 0.0.0.0 --port 8000

env_variables:
  OLLAMA_SERVER_URL: "https://ollamaapi-ollama-494205248522.us-central1.run.app/"  # Hosted Ollama URL

env: standard  # Use the standard environment
